# Site settings
title: Junkship
email: glenn.conner@junkship.net
description: > # this means to ignore newlines until "baseurl:"
  Creating a procedurally generated universe, one algorithm at a time.
#baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://junkship.net" # the base hostname & protocol for your site
twitter_username: mr_sharpoblunto
github_username:  mrsharpoblunto
permalink: /News/:year/:month/:day/:title.html
paginate: 5 
paginate_path: "/page:num"
setupversion: "0.2.30"
timezone: UTC
plugins: 
  - jekyll-redirect-from
  - jekyll-paginate
# Build settings
markdown: kramdown
